---
title: "Multiple Pages"
output: flexdashboard::flex_dashboard
---


```{r setup, include=FALSE}
library(flexdashboard)
source("R/rikolto.R")
source("waffle.R")
source("ProductionCommercialization.R")
library(DT)
```


Map
=====================================  
 
### Rikolto Participants
    
```{r}
map
```

Demographics 
=====================================     
    
Column {data-width=600}
-------------------------------------
    
### 
    
```{r}
ggplotly(prod_org)
```
   
Column {data-width=400}
-------------------------------------
   
### Chart 2

```{r}
counts %>% 
    DT::datatable()
```   
 
### Chart 3
    
```{r}
ggplotly(age)
```


Production & Commercialization {data-orientation=rows}
=====================================     
   
Row {data-height=800}
-------------------------------------

###

```{r}
productivity %>% 
    DT::datatable()
```

###

```{r}

```

Row {data-height=200}
-------------------------------------
   
### 

```{r}

```   
    
### 

```{r}

```

Planning & Investment {data-orientation=rows}
=====================================     
   
Row {data-height=800}
-------------------------------------

###

```{r}

```

###

```{r}

```

Row {data-height=200}
-------------------------------------
   
### 

```{r}

```   
    
### 

```{r}

```

Inclusiveness & Gender {data-orientation=rows}
=====================================     
   
Row {data-height=800}
-------------------------------------

###

```{r}

```

###

```{r}

```

Row {data-height=200}
-------------------------------------
   
### 

```{r}

```   
    
### 

```{r}

```

Resilience {data-orientation=rows}
=====================================     
   
Row {data-height=800}
-------------------------------------

###

```{r}

```

###

```{r}

```

Row {data-height=200}
-------------------------------------
   
### 

```{r}

```   
    
### 

```{r}

```
